name = "SuperResolution"
uuid = "3421342c-53fc-4d84-a0ef-1801cc3d8243"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]
version = "0.0.3"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
TinyMachines = "5d0fdf5f-995e-4f1b-a9e8-363392c4fe32"

[compat]
Flux = "0.16.5"
TinyMachines = "0.3"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
